# -*- coding: utf-8 -*-
"""=WomenClothinReview.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hAs9O4hbkFOBsQ3cRfWw_Lg1WPXG3kZI

**WOMEN CLOTH REVIEWS**

**The multinomial Naive Bayes classifier is suitable for classsification with discrete features (eg., word counts for text classification).The multinomial distribution normally requires interegr fetaure counts.Howevere, in practice, fractional counts such as tf-df may also work.**

**Import Library**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""**Import Dataset**"""

df = pd.read_csv('/content/Women_clothes_1.csv', encoding = "ISO-8859-1")
df.head()

df.info()

df.shape

"""**Missing values**

**Remove missing values in Reviews with No Review text**
"""

df.isna().sum()

"""**Define Target (y) and Feature (x)**"""

df.columns

x = df['Review']
y = df['Rating']

df['Rating'].value_counts()



"""**Train Test Split**"""

import numpy as np
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=2529)

X_train.shape, X_train.shape